<a href="https://colab.research.google.com/github/kbyc/UDEMY-Learning/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource Notebook:

In [1]:
print('Hello')

Hello


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [3]:
## Introduction to Tensors

In [4]:
# scalar - has only magnitude (single number)
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
 # Find out the dimensions for scalar
 scalar.ndim

0

In [6]:
# Scalar has no dimensions

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector - has both a magnitude and a direction
vector = torch.tensor([7,7])

In [9]:
vector.ndim
# number of dimensions (think about it as number of pair of squere brackets[])

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

 ### Random Tensors

 Why random tensors? 

 Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to bettwe represent the data

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [19]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7635, 0.9514, 0.5856, 0.7666],
        [0.7701, 0.8654, 0.3148, 0.1468],
        [0.8275, 0.9968, 0.7451, 0.8252]])

In [20]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels (red, green, blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
torch.arange(start=0,end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like 
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**NOTE**: Tensor datatypes isone of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors nor right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor (e.g. float32, float16, float64)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
# Even if we specify as 'none' the default is 'float32'

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor #calculation was made despite that those two were nont the same datatype


tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors nor right datatype - to get datatype from the tensor, use `tensor.dtype`
2. Tensors not right shape - to get shape from the tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, use `tensor.device`



In [35]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0730, 0.1843, 0.5943, 0.5467],
        [0.8089, 0.8482, 0.2315, 0.1765],
        [0.0489, 0.7473, 0.5125, 0.9713]])

In [36]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype f tensor: {some_tensor.dtype}') #default is float32
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on:{some_tensor.device}') #default is CPU

tensor([[0.0730, 0.1843, 0.5943, 0.5467],
        [0.8089, 0.8482, 0.2315, 0.1765],
        [0.0489, 0.7473, 0.5125, 0.9713]])
Datatype f tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [37]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [41]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html 

Matrix multiplication symilation: http://matrixmultiplication.xyz/

There are two main rules that performing matrix multiplication needs to satisfy (otherwise we get an error):
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

--> The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.

2. The resulting matrix has a shape of **outer dimenstions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [43]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f'Equals: {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
# Matrix multiplication by hand 
1*1 + 2*2 + 3*3

14

In [46]:
tensor @ tensor # gives the same result as `torch.matmul`

tensor(14)

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 5.51 ms, sys: 91 µs, total: 5.6 ms
Wall time: 5.8 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 80 µs, sys: 0 ns, total: 80 µs
Wall time: 84.9 µs


tensor(14)

### One of the most common erros in deep learning: shape errors

In [52]:
 # Shapes for matrix multiplication
 tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])

 tensor_B = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])
 
 torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it'san alias for writing less code)


RuntimeError: ignored

In [53]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [54]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [55]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [56]:
tensor_B.T.shape

torch.Size([2, 3])

In [57]:
# The matrix multiplication operation works when tensor_B is trnasposed

print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Outout:\n')
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Outout:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [58]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [59]:
# FInd the min
torch.min(x)

tensor(0)

In [60]:
x.min()

tensor(0)

In [61]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [62]:
# Find the mean 
# The torch.mean() function requires a tensor of float32 datatype to work 
# So we need to conver our tensor from dtype=float64 (also calles longType) to dtype=float32 as we got an error when dtype is default float64
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [63]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [64]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
# Find the position in tensor that has the minumum value with argmin() -> returns index position of target tensor where minimum values occur
x.argmin()

tensor(0)

In [66]:
x[0]

tensor(0)

In [67]:
# Find the postion in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [68]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [69]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# Add an extra dimension 
x_reshaped = x.reshape(1,9) #we can also do (9,1) 
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
# Changing z changes x (because a view of a tensor shares the same memroy as the original input)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [73]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [74]:
# torch.squeeze() - removes all single dimensions from a target tensor 
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
x_reshaped.shape

torch.Size([1, 9])

In [76]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
x_reshaped.squeeze().shape

torch.Size([9])

In [78]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previosu shape: {x_reshaped.shape}')

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previosu shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [79]:
# torch.unsqueeze() - adds a single dimenstion to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [80]:
# torch.permute - rearranges the dimensions of a target tensor in a specifies order

x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0 (so we shits colour_channels to index 0, height to index 1, width to index 2)

print(f'Previosu shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')


Previosu shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [81]:
x_original

tensor([[[0.0842, 0.2834, 0.3812],
         [0.1012, 0.2303, 0.2511],
         [0.3303, 0.0118, 0.9675],
         ...,
         [0.8195, 0.6622, 0.1865],
         [0.0075, 0.1530, 0.6085],
         [0.9111, 0.3300, 0.1910]],

        [[0.4216, 0.5403, 0.9420],
         [0.4688, 0.8780, 0.1607],
         [0.2649, 0.9660, 0.3292],
         ...,
         [0.1360, 0.2092, 0.7498],
         [0.6004, 0.2671, 0.7205],
         [0.2626, 0.9317, 0.8185]],

        [[0.6611, 0.8064, 0.6250],
         [0.1630, 0.2246, 0.5803],
         [0.5049, 0.5956, 0.8920],
         ...,
         [0.0759, 0.8240, 0.6054],
         [0.9469, 0.4961, 0.3158],
         [0.9952, 0.3185, 0.7359]],

        ...,

        [[0.8849, 0.2795, 0.7759],
         [0.3826, 0.5347, 0.2227],
         [0.7500, 0.5875, 0.4869],
         ...,
         [0.8060, 0.2912, 0.9677],
         [0.7538, 0.7586, 0.8083],
         [0.9764, 0.1056, 0.2654]],

        [[0.6777, 0.9118, 0.9131],
         [0.4553, 0.5511, 0.4275],
         [0.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [82]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [83]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
# Let's index on the middle bracket (dim=1)
x[0][0] # it's the same as x[0,0]

tensor([1, 2, 3])

In [85]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [86]:
# You can also use ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [87]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [88]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [89]:
# Get index 0 of 0th and 1st dimension and all values of the 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it 

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [90]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting form numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
array.dtype

dtype('float64')

In [92]:
tensor.dtype

torch.float64

In [93]:
torch.arange(1.0,8.0).dtype

torch.float32

In [94]:
# change the value of array and what will this do to 'tensor'?
array = array + 1
array, tensor # tensor is not affected 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [96]:
# Change the tensor and what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor # they are not sharing memory so it is unchanged

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again..` 

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [97]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.6562, 0.1181, 0.4607, 0.4115],
        [0.2963, 0.6812, 0.5306, 0.5629],
        [0.8058, 0.4290, 0.9698, 0.3317]])
tensor([[0.6855, 0.3678, 0.8967, 0.6155],
        [0.7561, 0.2779, 0.6559, 0.4533],
        [0.6187, 0.5362, 0.7932, 0.1106]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [101]:
# Let's make some random but reproducible tensors

import torch
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky

### 1. Getting a GPU

1. Easiest - USe Google Colab for free GPU (options to upgrade as well)
2. Use your own GPU- takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options...
3. Use cloud computing - GCP, AWS, Azure, these servies allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refer to PyTorch setup documentation: xx

In [1]:
!nvidia-smi

Wed Nov 16 20:27:45 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access for PyTorch

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostics code:

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [5]:
# Setup device agnostic code
device = 'cuda'if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and modules on the GPU

The reason we want tensors/models on the GPU is because using GPU results in faster computations

In [8]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [11]:
# If tensor is on GPU, can't tranform it to NumPy
tensor_on_gpu.numpy() #NumPy is not working with GPU

TypeError: ignored

In [14]:
# To fix the GPU tesnor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])